### ISSUE TITLE
Crash with Carpet mod installed

### ISSUE THREAD

**Issue by SticksS123** [MORIMORI0317/BEStyleWither#1]
[01:25:16] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.8
[01:25:16] [ForkJoinPool-1-worker-8/WARN]: Mod create uses the version mc1.18.2_v0.4.1+637 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'mc1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[01:25:16] [ForkJoinPool-1-worker-5/WARN]: Mod fabrishot uses the version ${version} which isn't compatible with Loader's extended semantic version format (Could not parse version number component '${version}'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[01:25:16] [ForkJoinPool-1-worker-1/WARN]: Mod mavm uses the version 1.0.8a which isn't compatible with Loader's extended semantic version format (Could not parse version number component '8a'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[01:25:16] [ForkJoinPool-1-worker-6/WARN]: Mod registrate-fabric uses the version MC1.18.2-1.0.3 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'MC1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[01:25:17] [main/INFO]: Dependencies overridden for fabric, colormatic, debugify
[01:25:17] [main/WARN]: Warnings were found!
 - Mod 'Fabric API' (fabric) 0.57.0+1.18.2 recommends version latest of Fabulously Optimized, which is missing!
	 - You should install version latest of Fabulously Optimized for the optimal experience.
[01:25:17] [main/INFO]: Loading 210 mods:
	- advanced_runtime_resource_pack 0.5.5 via enhancedblockentities
	- advancementinfo 1.18.2-fabric0.47.10-1.3.1
	- anchor 1.1.0
	- animatica 0.5+1.18.2
	- antighost 1.18.2-fabric0.47.10-1.1.4
	- architectury 4.5.75
	- axolotlitemfix 1.1.3
	- bclib 1.4.7
	- bedrodium 0.2
	- bestylewither 1.1
	- betterdeserttemples 1.18.2-Fabric-1.1.0
	- betterdungeons 1.18.2-Fabric-2.1.0
	- betterend 1.1.1
	- bettermineshafts 1.18.2-Fabric-2.1.4
	- bettermounthud 1.1.4
	- betterstrongholds 1.18.2-Fabric-2.1.1
	- bettervillage 1.0.1
	- betterwitchhuts 1.18.2-Fabric-1.0
	- blast 1.9.1
	- borderlessmining 1.1.2+1.18.2
	- bosses_of_mass_destruction 1.3.7-1.18.2
	- caffeineconfig 1.1.0 via sodium-extra
	- cardinal-components 4.1.4
	- cardinal-components-base 4.1.4 via cardinal-components
	- cardinal-components-block 4.1.4 via cardinal-components
	- cardinal-components-chunk 4.1.4 via cardinal-components
	- cardinal-components-entity 4.1.4 via cardinal-components
	- cardinal-components-item 4.1.4 via cardinal-components
	- cardinal-components-level 4.1.4 via cardinal-components
	- cardinal-components-scoreboard 4.1.4 via cardinal-components
	- cardinal-components-world 4.1.4 via cardinal-components
	- carpet 1.4.69
	- cem 0.7.1
	- ciif 1.0.0
	- citresewn 1.1.0+1.18.2
	- citresewn-defaults 1.1.0+1.18.2 via citresewn
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 6.2.62
	- com_electronwill_night-config_core 3.6.5 via globaldataandresourcepacks
	- com_electronwill_night-config_toml 3.6.5 via globaldataandresourcepacks
	- com_eliotlash_mclib_mclib 18 via geckolib3
	- com_eliotlash_molang_molang 18 via geckolib3
	- com_github_llamalad7_mixinextras 0.0.10 via debugify
	- com_github_ramanrajarathinam_native-utils 1.0.0 via screencopy
	- com_google_code_findbugs_jsr305 3.0.2 via create
	- com_moandjiezana_toml_toml4j 0.7.2 via dynamicfps
	- completeconfig 1.0.0 via cem
	- continuity 2.0.0+1.18.2
	- cosmetic-armor 1.3.1
	- crawl 0.10.6
	- create mc1.18.2_v0.4.1+637
	- crowdin-translate 1.4+1.18.2 via antighost
	- cull-less-leaves 1.0.1
	- dcch 1.0
	- debugify 1.11.0
	- disable_custom_worlds_advice 2.0
	- dripstone_fluid_lib 1.2.0 via milk_plus
	- dual_riders 1.1.1
	- dynamicfps 2.1.0
	- effective 1.2.1
	- eldritch_mobs 1.11.0
	- enhancedblockentities 0.7.1+1.18.2
	- entity_texture_features 3.1.4-mc1.18.x
	- entityculling 1.5.1
	- expandeddelight 0.1.9
	- fabric 0.57.0+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric
	- fabric-api-lookup-api-v1 1.6.2+2373a54560 via fabric
	- fabric-biome-api-v1 8.0.6+651bcc5960 via fabric
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.22+d7c144a860 via fabric
	- fabric-content-registries-v0 3.1.1+c85f2e3860 via fabric
	- fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric
	- fabric-crash-report-info-v1 0.2.1+ee261a3e60 via fabric
	- fabric-data-generation-api-v1 3.0.0+9fcb91d260 via fabric
	- fabric-dimensions-v1 2.1.20+489d6f8260 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.18+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.5.1+6c4e5d0960 via fabric
	- fabric-item-groups-v0 0.3.14+91896a4960 via fabric
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric
	- fabric-language-kotlin 1.8.1+kotlin.1.7.0
	- fabric-lifecycle-events-v1 2.1.0+cc71601c60 via fabric
	- fabric-loot-api-v2 1.1.0+1997ad1260 via fabric
	- fabric-loot-tables-v1 1.1.2+e747827960 via fabric
	- fabric-mining-level-api-v1 2.1.4+cc71601c60 via fabric
	- fabric-models-v0 0.3.6+d7c144a860 via fabric
	- fabric-networking-api-v1 1.0.22+e6b169eb60 via fabric
	- fabric-networking-v0 0.3.9+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.1.3+032c981d60 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-registry-sync-v0 0.9.9+0d9ab37260 via fabric
	- fabric-renderer-api-v1 0.4.13+d882b91560 via fabric
	- fabric-renderer-indigo 0.5.2+d005b03a60 via fabric
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric
	- fabric-rendering-v1 1.10.7+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric
	- fabric-resource-loader-v0 0.5.2+446e059560 via fabric
	- fabric-screen-api-v1 1.0.10+d882b91560 via fabric
	- fabric-screen-handler-api-v1 1.2.1+1f6558e860 via fabric
	- fabric-textures-v0 1.0.12+3ac43d9560 via fabric
	- fabric-transfer-api-v1 1.6.3+f4563ac860 via fabric
	- fabric-transitive-access-wideners-v1 1.1.0+e747827960 via fabric
	- fabricloader 0.14.8
	- fabrishot ${version}
	- fake-player-api 0.3.0 via create
	- farmersdelight 1.18.2-0.2.1
	- farsight 1.18-1.9
	- feature_nbt_deadlock_be_gone 2.0.0+1.18.2-rc1
	- ferritecore 4.2.1
	- fiber 0.23.0-2 via patchouli
	- flytre_lib 1.8.1
	- flywheel 1.18-0.7.0.26 via create
	- forge_tags 2.1 via create
	- forgeconfigapiport 3.2.0
	- geckolib3 3.0.50
	- globaldataandresourcepacks 1.12.2.1
	- here-be-no-dragons 1.0.0 via twilightforest
	- illegal 1.1.0
	- incendium 5.0.4
	- indium 1.0.6+mc1.18.2
	- io_github_imurx_arboard 1.1.0 via screencopy
	- iris 1.2.5
	- isxander-main-menu-credits 1.1.1
	- itemmodelfix 1.0.3+1.18
	- java 17
	- javax_annotation_javax_annotation-api 1.3.2 via twilightforest
	- jukeboxparticles 1.0.0
	- languagereload 1.2.1
	- lazydfu 0.1.2
	- libraryferret 1.0.3
	- lithium 0.7.10
	- maelstrom_library 1.2.4-1.18.2 via bosses_of_mass_destruction
	- mavm 1.0.8a
	- melonslabs 1.1.0+1.18.2
	- memoryleakfix 1.18.2-0.3.5
	- midnightlib 0.4.0 via puzzle
	- milk 0.3.2 via create
	- milk_plus 3.0.1
	- minecraft 1.18.2
	- mm 2.3 via crawl
	- mobbattle 1.18.2-2.4.2
	- modmenu 3.2.3
	- morechathistory 1.1.0
	- multipart_entities 1.1.5-1.18.2 via bosses_of_mass_destruction
	- nbtcrafting 2.1.3+mc1.18.2 via ciif
	- noaispawneggs 11.0.1
	- noindium 1.0.1+1.18.2 via create
	- notenoughanimations 1.6.0
	- omega-config 1.2.3-1.18.1 via noindium
	- onsoulfire 1.18-3
	- org_anarres_jcpp 1.4.14 via iris
	- org_aperlambda_lambdajcommon 1.8.1 via spruceui
	- org_jetbrains_kotlin_kotlin-reflect 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.3 via fabric-language-kotlin
	- org_joml_joml 1.10.2 via sodium
	- panorama_tweaker 1.1.0+mc1.18.1
	- patchouli 1.18.2-71.1-FABRIC
	- polaroidcamera 1.2.9
	- pollen 1.4.4
	- porting_lib 1.1.342-beta+1.18.2-dev.dd61cdc via twilightforest
	- puzzle 1.3.0
	- puzzle-base 1.3.0 via puzzle
	- puzzle-gui 1.3.0 via puzzle
	- puzzle-models 1.3.0 via puzzle
	- puzzle-splashscreen 1.3.0 via puzzle
	- puzzleslib 3.3.5
	- reach-entity-attributes 2.1.1 via create
	- reeses-sodium-options 1.4.3+mc1.18.2-build.42
	- registrate-fabric MC1.18.2-1.0.3 via create
	- screencopy 1.1.0
	- seedfix 1.0.1
	- serialization_hooks 0.2.0+1.18.f5d4aa6 via porting_lib
	- server-hats 0.9
	- simplehats 1.18.2-0.1.2
	- smoothboot 1.18.2-1.7.0
	- sodium 0.4.1+build.15
	- sodium-extra 0.4.5+mc1.18.2-build.42
	- spruceui 3.3.0+1.17 via enhancedblockentities
	- spyglass-improvements 1.2+mc1.18.2+fabric
	- starlight 1.0.2+fabric.89b8d9f
	- structory 1.0.0
	- tooltipfix 1.0.4-1.18
	- trinkets 3.3.1
	- twilightforest 4.1.251
	- unsaddle 0.1.0+1.17
	- unsaddle-core 0.1.0 via unsaddle
	- visualworkbench 3.3.0
	- waveycapes 1.2.0
	- weaponmaster 1-18-x
	- wildlife 1.18.2-2.0
	- yosbr 0.1.1
	- yungsapi 1.18.2-Fabric-2.0.8
[01:25:18] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/range/curseforge/minecraft/Install/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[01:25:18] [main/INFO]: Compatibility level set to JAVA_16
[01:25:18] [main/INFO]: Compatibility level set to JAVA_17
[01:25:18] [main/WARN]: Reference map 'axolotl-item-fix-refmap.json' for axolotlitemfix.mixins.json could not be read. If this is a development environment you can ignore this message
[01:25:19] [main/INFO]: Preloading Debugify
[01:25:19] [main/INFO]: Done.
[01:25:19] [main/WARN]: Reference map 'dual_riders-1.18.2-1.1.1-fabric-refmap.json' for dual_riders-fabric.mixins.json could not be read. If this is a development environment you can ignore this message
[01:25:19] [main/INFO]: Loaded configuration file for Lithium: 102 options available, 1 override(s) found
[01:25:19] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[01:25:19] [main/INFO]: Loaded configuration file for Sodium Extra: 27 options available, 0 override(s) found
[01:25:19] [main/WARN]: Reference map 'wildlife-refmap.json' for wildlife.mixins.json could not be read. If this is a development environment you can ignore this message
[01:25:21] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[01:25:21] [main/WARN]: Error loading class: me/juancarloscp52/bedrockify/client/features/panoramaBackground/BedrockifyRotatingCubeMapRenderer (java.lang.ClassNotFoundException: me/juancarloscp52/bedrockify/client/features/panoramaBackground/BedrockifyRotatingCubeMapRenderer)
[01:25:21] [main/WARN]: @Mixin target me.juancarloscp52.bedrockify.client.features.panoramaBackground.BedrockifyRotatingCubeMapRenderer was not found panorama_tweaker.mixins.json:compat.BedrockifyRotatingCubeMapRendererMixin from mod panorama_tweaker
[01:25:21] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[01:25:22] [main/INFO]: I used the json to destroy the json
[01:25:22] [main/INFO]: Trying to switch memory allocators to work around memory leaks present with Jemalloc 5.0.0 through 5.2.0 on Windows
[01:25:22] [main/INFO]: Smooth Boot config initialized
[01:25:23] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[01:25:24] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[01:25:25] [main/WARN]: Method overwrite conflict for getHotbarSlots in weaponmaster.mixins.json:ClientPlayerMixin from mod weaponmaster, previously written by com.minecraftserverzone.weaponmaster.mixin.PlayerEntityMixin. Skipping method.
[01:25:25] [main/WARN]: Method overwrite conflict for setHotbarSlot in weaponmaster.mixins.json:ClientPlayerMixin from mod weaponmaster, previously written by com.minecraftserverzone.weaponmaster.mixin.PlayerEntityMixin. Skipping method.
[01:25:25] [main/WARN]: Method overwrite conflict for getBlackList in weaponmaster.mixins.json:ClientPlayerMixin from mod weaponmaster, previously written by com.minecraftserverzone.weaponmaster.mixin.PlayerEntityMixin. Skipping method.
[01:25:25] [main/WARN]: Method overwrite conflict for setBlackList in weaponmaster.mixins.json:ClientPlayerMixin from mod weaponmaster, previously written by com.minecraftserverzone.weaponmaster.mixin.PlayerEntityMixin. Skipping method.
[01:25:25] [main/WARN]: Method overwrite conflict for getToggleSlot in weaponmaster.mixins.json:ClientPlayerMixin from mod weaponmaster, previously written by com.minecraftserverzone.weaponmaster.mixin.PlayerEntityMixin. Skipping method.
[01:25:25] [main/WARN]: Method overwrite conflict for setToggleSlot in weaponmaster.mixins.json:ClientPlayerMixin from mod weaponmaster, previously written by com.minecraftserverzone.weaponmaster.mixin.PlayerEntityMixin. Skipping method.
[01:25:25] [main/WARN]: Method overwrite conflict for getSelectedSlot in weaponmaster.mixins.json:ClientPlayerMixin from mod weaponmaster, previously written by com.minecraftserverzone.weaponmaster.mixin.PlayerEntityMixin. Skipping method.
[01:25:25] [main/WARN]: Method overwrite conflict for setSelectedSlot in weaponmaster.mixins.json:ClientPlayerMixin from mod weaponmaster, previously written by com.minecraftserverzone.weaponmaster.mixin.PlayerEntityMixin. Skipping method.
[01:25:26] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=2 on dripstone_fluid_lib.mixins.json:MinecraftClientMixin from mod dripstone_fluid_lib::handler$cao000$dripstone_fluid_lib$handleParticles exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[01:25:28] [main/WARN]: @Final field field_10709:Lnet/minecraft/class_2758; in melonslabs.mixins.json:CactusMixin from mod melonslabs should be final
[01:25:29] [main/WARN]: Method overwrite conflict for setTranslation in flywheel.fabric.mixins.json:Matrix4fMixin from mod flywheel, previously written by io.github.fabricators_of_create.porting_lib.mixin.common.Matrix4fMixin. Skipping method.
[01:25:30] [main/WARN]: @Redirect conflict. Skipping carpet.mixins.json:WitherBoss_extremeMixin from mod carpet->@Redirect::nextFloatAmplfied(Ljava/util/Random;)F with priority 1000, already redirected by bestylewither-common.mixins.json:WitherBossMixin from mod bestylewither->@Redirect::injected(Ljava/util/Random;)F with priority 1000
[01:25:30] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[client-intermediary.jar:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[client-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.1.27.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[client-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:19) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:86) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:85) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[fabric-loader-0.14.8-1.18.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1528 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:433) ~[client-intermediary.jar:?]
	at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[client-intermediary.jar:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[client-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.1.27.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[client-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:19) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:86) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:85) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[fabric-loader-0.14.8-1.18.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:433) ~[client-intermediary.jar:?]
	at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[client-intermediary.jar:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[client-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.1.27.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[client-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:19) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:86) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:85) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[fabric-loader-0.14.8-1.18.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector nextFloatAmplfied(Ljava/util/Random;)F in carpet.mixins.json:WitherBoss_extremeMixin from mod carpet failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap fabric-carpet-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:433) ~[client-intermediary.jar:?]
	at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[client-intermediary.jar:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[client-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.1.27.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[client-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:19) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:86) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:85) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[fabric-loader-0.14.8-1.18.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 2 more

**Comment by MORIMORI0317** [comment]
Released a fixed version!
https://www.curseforge.com/minecraft/mc-mods/be-style-wither/files/3857271
